$(document).ready(function(){
    
$(".box_01").on("click",function(){
    $(this).siblings(".view01").stop().fadeIn()
})
$(".box_02").on("click",function(){
    $(this).siblings(".view02").stop().fadeIn()
})
$(".box_03").on("click",function(){
    $(this).siblings(".view03").stop().fadeIn()
})
$(".box_04").on("click",function(){
    $(this).siblings(".view04").stop().fadeIn()
})
$(".viewX").on("click",function(){
    $(".view").fadeOut()
})
$(".bgClose").on("click",function(){
    $(".view").fadeOut()
})
AOS.init();
})//끝